### ISSUE TITLE
Link on website?

### ISSUE THREAD

**Issue by bobappleyard** [JohnWCartmell/ERScript#5]
I was looking at http://entitymodelling.org and I couldn't find a link to this repository there.

I think it would be a good idea to include such a link, or make it more prominent if it's already there.

**Comment by JohnWCartmell** [comment]
Yes I will do that thanks. I will add a chapter on the software and include a download of the built ERScript software.

**Comment by JohnWCartmell** [comment]
Link added to  http://www.entitymodelling.org/concept2code/overview.html 21 December 2017. 
This page also contains a zip file download of ERScript_r3. This is the built scripting software - built from release tagged ERScript_r3 - and also including jing and saxon jar files.
